name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Cloning repository
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: make
    - name: publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ./components/sdk/.npmrc
        make publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
